@ECHO OFF
SET BAT64=Q09MT1IgMEENClNFVCBBVFRFTVBUUz0zDQpTRVRMT0NBTCBFTkFCTEVERUxBWUVERVhQQU5TSU9ODQpARUNITyBPRkYNCkNMUw0KRUNITyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQpFQ0hPICBDT05WRVJUSU5HIERPQ1VNRU5UUw0KRUNITyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQpGT1IgL0YgInRva2Vucz0yKiBza2lwPTIiICUlYSBpbiAoJ1JFRyBRVUVSWSAiSEtFWV9MT0NBTF9NQUNISU5FXFNPRlRXQVJFXE1pY3Jvc29mdFxXaW5kb3dzXEN1cnJlbnRWZXJzaW9uXEFwcCBQYXRoc1xFWENFTC5FWEUiIC92IFBhdGgnKSBkbyBTRVQgTE9DPSUlYmV4Y2VsY252LmV4ZQ0KDQpTRVQgRkk9JTENClNFVCBGTz0lRkk6fjAsLTEleCINCg0KOk1haW4NCklGIEVYSVNUICVGTyUgKA0KCUVDSE8gJUZPJQ0KCUVDSE8gWExTWCBGaWxlIGFscmVhZHkgZXhpc3RzLCBhYm9ydGluZyBjb252ZXJzaW9uLi4uDQoJQFRJTUVPVVQgMw0KCUVDSE8gRXhpdGluZw0KCUVYSVQNCikgRUxTRSAoDQoJRUNITyBDcmVhdGluZyBGaWxlICVGTyUNCglFQ0hPIFBsZWFzZSBXYWl0Li4uDQoJU0VUIE9SREVSVElNRVI9MQ0KCTpFWEVPUkRFUg0KCQlJRiBFWElTVCAlQVBQREFUQSVcWExTQ1whT1JERVJUSU1FUiEuVE1QICgNCgkJCVNFVCAvQSBPUkRFUlRJTUVSKz0xDQoJCQlHT1RPIEVYRU9SREVSDQoJCQkpDQoJCUVDSE8gLj4lQVBQREFUQSVcWExTQ1whT1JERVJUSU1FUiEuVE1QIDI+bnVsDQoJCVRJTUVPVVQgL1QgIU9SREVSVElNRVIhIC9OT0JSRUFLDQoJCURFTCAvRiAlQVBQREFUQSVcWExTQ1whT1JERVJUSU1FUiEuVE1QIDI+bnVsDQoJIiVMT0MlIiAtb2ljZSAlRkklICVGTyUNCglHT1RPIEZBSUxTQUZFDQoJKQ0KOkZBSUxTQUZFDQpJRiBFWElTVCAlRk8lICgNCglFQ0hPIENvbnZlcnNpb24gQ29tcGxldGUhDQoJRUNITyBFeGl0aW5nDQoJQFRJTUVPVVQgMyAvTk9CUkVBSw0KCUVYSVQNCikgRUxTRSAoDQoJSUYgIUFUVEVNUFRTISBHVFIgMCAoDQoJCVNFVCAvQSBBVFRFTVBUUy09MQ0KCQlHT1RPIE1BSU4NCgkpIEVMU0UgKA0KCQlFQ0hPIENvbnZlcnNpb24gRmFpbGVkLg0KCQlAVElNRU9VVCAxIC9OT0JSRUFLDQoJKQ0KKQ==
SET T=EASY CONTEXT MENU XLS TO XLSX CONVERTER (UNOFFICIAL 20/07/2021)
SET I=SUCCESSFULLY INSTALLED
SET R=SUCCESSFULLY REMOVED
SET S= 
SET INPA=XLSC
SET POINTER=%APPDATA%\XLSC
SET "POINTER=%POINTER:\=/%"
SET ADP=^%%APPDATA^%%\XLSC\XLSC.bat
SET ADQ=""%%1""
COLOR 97
CLS
ECHO %T%
ECHO.
ECHO.
FOR /F "tokens=2* skip=2" %%a in ('REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\EXCEL.EXE" /v Path') do SET LOC=%%bexcelcnv.exe
IF %ERRORLEVEL%==0 GOTO MENU
ECHO FAILED TO DETECT MICROSOFT EXCEL INSTALLATION
ECHO.
ECHO ABORTING SETUP
ECHO.
PAUSE
GOTO END

:MENU
ECHO %S%(INSTALLATION DETECTED AT %LOC%)
ECHO.
ECHO %S%...........................................................
ECHO %S%Type 1, 2, or 0 to select option and then ENTER to confirm
ECHO %S%...........................................................
ECHO.
IF NOT EXIST %APPDATA%\%INPA%\XLSC.bat ECHO %S%1 - Install Converter
IF EXIST %APPDATA%\%INPA%\XLSC.bat ECHO %S%1 - (Re)install Converter
IF EXIST %APPDATA%\%INPA%\XLSC.bat ECHO %S%2 - Remove Converter
IF NOT EXIST %APPDATA%\%INPA%\XLSC.bat ECHO %S%2 - Remove Converter (Clean-up Only)
ECHO %S%0 - EXIT
ECHO.
ECHO.
SET /P M="ENTER CHOICE:  "
IF %M%==1 GOTO INSTALL
IF %M%==2 GOTO UNINSTALL
IF %M%==0 GOTO END

:INSTALL
CLS
ECHO %T%
RMDIR %APPDATA%\%INPA% /S /Q 2>NUL
MKDIR %APPDATA%\%INPA%
ECHO %APPDATA%\%INPA%\BAT64
ECHO %BAT64% 1>%APPDATA%\%INPA%\BAT64 2>NUL
CERTUTIL -DECODE %APPDATA%\%INPA%\BAT64 %APPDATA%\%INPA%\XLSC.bat
DEL %APPDATA%\%INPA%\BAT64 2>NUL
ECHO %S%Conversion Batch File Saved: %APPDATA%\%INPA%\XLSC.bat
REG ADD "HKEY_CURRENT_USER\SOFTWARE\Classes\Excel.Sheet.8\shell\Convert XLS to XLSX\command" /ve /t REG_EXPAND_SZ /d "%ADP% %ADQ%" /f
REG ADD "HKEY_CURRENT_USER\SOFTWARE\Classes\Excel.Sheet.8\shell\Convert XLS to XLSX" /v "Icon" /t REG_SZ /d "%LOC%" /f >nul 2>nul
ECHO Registry Key Added
ECHO %S%%I%
ECHO.
PAUSE
CLS
ECHO %T%
ECHO %S%%I%
ECHO.
GOTO MENU

:UNINSTALL
CLS
ECHO %T%
RMDIR %APPDATA%\%INPA% /S /Q 2>NUL
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Classes\Excel.Sheet.8\shell\Convert XLS to XLSX" /f
ECHO %S%%R%
ECHO.
PAUSE
CLS
ECHO %T%
ECHO %S%%I%
ECHO.
GOTO MENU

:END